[tool.poetry]
name = "khala-bq"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "gcp-sample"}]

[tool.poetry.dependencies]
python = "^3.11"
google-cloud-bigquery-migration = "^0.11.0"

[tool.poetry.group.dev.dependencies]
setuptools = "^67.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
