name: nodejs tests
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nodejs/format
    steps:
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - uses: actions/checkout@main
      - run: npm install
      - run: npm test
        env:
          API_KEY: ${{secrets.API_KEY}}
