name: python tests
on: push
jobs:
  core:
    runs-on: ubuntu-latest
    environment: data
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          tests: py/tests
          test-entry-point: pytest --ignore=adc/
          working-directory: py
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          API_KEY: ${{secrets.API_KEY}}
  bq:
    runs-on: ubuntu-latest
    environment: data
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          tests: bigQuery/py/tests
          test-entry-point: pytest --ignore=migrate_test.py
          working-directory: bigQuery/py
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}